"""nova versão, tabela de usuário e uuid v6

Revision ID: 47295776065e
Revises: 2ec839e43450
Create Date: 2025-10-29 23:09:56.296774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47295776065e'
down_revision: Union[str, Sequence[str], None] = '2ec839e43450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_users_address'), table_name='users')
    op.drop_index(op.f('ix_users_birthDate'), table_name='users')
    op.drop_index(op.f('ix_users_emailAddress'), table_name='users')
    op.drop_index(op.f('ix_users_firstName'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_lastName'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_phoneNumber'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_userName'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def upgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('userName', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('birthDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('emailAddress', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('phoneNumber', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('lastName', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_userName'), 'users', ['userName'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_phoneNumber'), 'users', ['phoneNumber'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_lastName'), 'users', ['lastName'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_firstName'), 'users', ['firstName'], unique=False)
    op.create_index(op.f('ix_users_emailAddress'), 'users', ['emailAddress'], unique=False)
    op.create_index(op.f('ix_users_birthDate'), 'users', ['birthDate'], unique=False)
    op.create_index(op.f('ix_users_address'), 'users', ['address'], unique=False)
    # ### end Alembic commands ###
