"""Adiciona coluna user_id na tabela bookings

Revision ID: ed8582a05a8f
Revises: 58277f688b52
Create Date: 2025-11-10 22:09:12.374965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed8582a05a8f'
down_revision: Union[str, Sequence[str], None] = '58277f688b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.add_column('bookings', sa.Column('user_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_column('bookings', 'user_id')
    op.create_table('reservas',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_checkin', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data_checkout', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('reservas_room_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reservas_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reservas_pkey'))
    )
    # ### end Alembic commands ###
