"""Add created_at to Booking

Revision ID: f279fb813d23
Revises: ed8582a05a8f
Create Date: 2025-11-12 23:57:08.862414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f279fb813d23'
down_revision: Union[str, Sequence[str], None] = 'ed8582a05a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'created_at')
    # ### end Alembic commands ###
